// tslint:disable
export let data: object[] = [
    { x: 1, yval: 5 },
    { x: 2, yval: 6 },
    { x: 3, yval: 5 },
    { x: 4, yval: 7 },
    { x: 5, yval: 4 },
    { x: 6, yval: 3 },
    { x: 7, yval: 9 },
    { x: 8, yval: 5 },
    { x: 9, yval: 6 },
    { x: 10, yval: 5 },
    { x: 11, yval: 7 },
    { x: 12, yval: 8 },
    { x: 13, yval: 4 },
    { x: 14, yval: 5 },
    { x: 15, yval: 3 },
    { x: 16, yval: 4 },
    { x: 17, yval: 11 },
    { x: 18, yval: 10 },
    { x: 19, yval: 2 },
    { x: 20, yval: 12 },
    { x: 21, yval: 4 },
    { x: 22, yval: 7 },
    { x: 23, yval: 6 },
    { x: 24, yval: 8 }
];
export let data2: object[] = [
    { x: 1, xval: 'Jan', yval: 34 },
    { x: 2, xval: 'Feb', yval: 36 },
    { x: 3, xval: 'Mar', yval: 32 },
    { x: 4, xval: 'Apr', yval: 35 },
    { x: 5, xval: 'May', yval: 40 },
    { x: 6, xval: 'Jun', yval: 38 },
    { x: 7, xval: 'Jul', yval: 33 },
    { x: 8, xval: 'Aug', yval: 37 },
    { x: 9, xval: 'Sep', yval: 34 },
    { x: 10, xval: 'Oct', yval: 31 },
    { x: 11, xval: 'Nov', yval: 30 },
    { x: 12, xval: 'Dec', yval: 29 }
];
export let data3: object[] = [
    { x: 1, xval: 'Jan', yval: 10 },
    { x: 2, xval: 'Feb', yval: 6 },
    { x: 3, xval: 'Mar', yval: 8 },
    { x: 4, xval: 'Apr', yval: -5 },
    { x: 5, xval: 'May', yval: 11 },
    { x: 6, xval: 'Jun', yval: 5 },
    { x: 7, xval: 'Jul', yval: -2 },
    { x: 8, xval: 'Aug', yval: 7 },
    { x: 9, xval: 'Sep', yval: -3 },
    { x: 10, xval: 'Oct', yval: 6 },
    { x: 11, xval: 'Nov', yval: 8 },
    { x: 12, xval: 'Dec', yval: 10 }    
];