export let taskDetails: object[] = [
    {
        Id: "Task 1",
        Title: "Task - 29001",
        Status: "Open",
        Summary: "Analyze the new requirements gathered from the customer",
        Type: "Story",
        Priority: "Low",
        CardTags: "Analyze, Customer",
        Estimate: 3.5,
        Assignee: "Nancy Davloio",
        AssigneeKey: "Nancy Davloio",
        RankId: 1,
        Color: "#8b447a",
        ClassName: "e-story, e-low, e-nancy",
        Timeline: "2024-06-20 to 2024-06-25",
        AssigneeAvailability: true
    },
    {
        Id: "Task 2",
        Title: "Task - 29002",
        Status: "In Progress",
        Summary: "Improve application performance",
        Type: "Improvement",
        Priority: "Normal",
        CardTags: "Improvement",
        Estimate: 6,
        Assignee: "Andrew Fuller",
        AssigneeKey: "Andrew Fuller",
        RankId: 1,
        Color: "#7d7297",
        ClassName: "e-improvement, e-normal, e-andrew",
        Timeline: "2024-06-20 to 2024-06-26",
        AssigneeAvailability: true
    },
    {
        Id: "Task 3",
        Title: "Task - 29003",
        Status: "Open",
        Summary: "Arrange a web meeting with the customer to get new requirements",
        Type: "Others",
        Priority: "Critical",
        CardTags: "Meeting",
        Estimate: 5.5,
        Assignee: "Janet Leverling",
        AssigneeKey: "Janet Leverling",
        RankId: 2,
        Color: "#27AE60",
        ClassName: "e-others, e-critical, e-janet",
        Timeline: "2024-06-20 to 2024-06-25",
        AssigneeAvailability: false
    },
    {
        Id: "Task 4",
        Title: "Task - 29004",
        Status: "In Progress",
        Summary: "Fix the issues reported in the IE browser",
        Type: "Bug",
        Priority: "Release Breaker",
        CardTags: "IE",
        Estimate: 2.5,
        Assignee: "Janet Leverling",
        AssigneeKey: "Janet Leverling",
        RankId: 2,
        Color: "#cc0000",
        ClassName: "e-bug, e-release, e-janet",
        Timeline: "2024-06-21 to 2024-06-23",
        AssigneeAvailability: false
    },
    {
        Id: "Task 5",
        Title: "Task - 29005",
        Status: "Review",
        Summary: "Fix the issues reported by the customer",
        Type: "Bug",
        Priority: "Low",
        CardTags: "Customer",
        Estimate: 3.5,
        Assignee: "Steven Walker",
        AssigneeKey: "Steven Walker",
        RankId: 1,
        Color: "#cc0000",
        ClassName: "e-bug, e-low, e-steven",
        Timeline: "2024-06-22 to 2024-06-25",
        AssigneeAvailability: true
    },
    {
        Id: "Task 6",
        Title: "Task - 29007",
        Status: "Validate",
        Summary: "Validate new requirements",
        Type: "Improvement",
        Priority: "Low",
        CardTags: "Validation",
        Estimate: 1.5,
        Assignee: "Robert King",
        AssigneeKey: "Robert King",
        RankId: 1,
        Color: "#7d7297",
        ClassName: "e-improvement, e-low, e-robert",
        Timeline: "2024-06-23 to 2024-06-24",
        AssigneeAvailability: false
    },
    {
        Id: "Task 7",
        Title: "Task - 29009",
        Status: "Review",
        Summary: "Fix the issues reported in Safari browser",
        Type: "Bug",
        Priority: "Release Breaker",
        CardTags: "Fix, Safari",
        Estimate: 1.5,
        Assignee: "Nancy Davloio",
        AssigneeKey: "Nancy Davloio",
        RankId: 2,
        Color: "#cc0000",
        ClassName: "e-bug, e-release, e-nancy",
        Timeline: "2024-06-23 to 2024-06-24",
        AssigneeAvailability: true
    },
    {
        Id: "Task 8",
        Title: "Task - 29010",
        Status: "Close",
        Summary: "Test the application in the IE browser",
        Type: "Story",
        Priority: "Low",
        CardTags: "Review, IE",
        Estimate: 5.5,
        Assignee: "Margaret Hamilt",
        AssigneeKey: "Margaret Hamilt",
        RankId: 3,
        Color: "#8b447a",
        ClassName: "e-story, e-low, e-Margaret",
        Timeline: "2024-06-20 to 2024-06-25",
        AssigneeAvailability: false
    },
    {
        Id: "Task 9",
        Title: "Task - 29011",
        Status: "Validate",
        Summary: "Validate the issues reported by the customer",
        Type: "Story",
        Priority: "High",
        CardTags: "Validation, Fix",
        Estimate: 1,
        Assignee: "Steven Walker",
        AssigneeKey: "Steven Walker",
        RankId: 1,
        Color: "#8b447a",
        ClassName: "e-story, e-low, e-nancy",
        Timeline: "2024-06-23 to 2024-06-24",
        AssigneeAvailability: true
    },
    {
        Id: "Task 10",
        Title: "Task - 29015",
        Status: "Open",
        Summary: "Show the retrieved data from the server in grid control",
        Type: "Story",
        Priority: "High",
        CardTags: "Database, SQL",
        Estimate: 5.5,
        Assignee: "Margaret Hamilt",
        AssigneeKey: "Margaret Hamilt",
        RankId: 4,
        Color: "#8b447a",
        ClassName: "e-story, e-high, e-steven",
        Timeline: "2024-06-22 to 2024-06-27",
        AssigneeAvailability: false
    },
    {
        Id: "Task 11",
        Title: "Task - 29016",
        Status: "In Progress",
        Summary: "Fix cannot open user’s default database SQL error.",
        Type: "Critical Bug",
        Priority: "High",
        CardTags: "Fix, SQL",
        Estimate: 2.5,
        Assignee: "Margaret Hamilt",
        AssigneeKey: "Margaret Hamilt",
        RankId: 4,
        Color: "#cc0000",
        ClassName: "e-bug, e-release, e-nancy",
        Timeline: "2024-06-20 to 2024-06-23",
        AssigneeAvailability: false
    },
    {
        Id: "Task 12",
        Title: "Task - 29017",
        Status: "Review",
        Summary: "Fix the issues reported in data binding.",
        Type: "Story",
        Priority: "Normal",
        CardTags: "Validation, Fix",
        Estimate: 3.5,
        Assignee: "Margaret Hamilt",
        AssigneeKey: "Margaret Hamilt",
        RankId: 4,
        Color: "#8b447a",
        ClassName: "e-story, e-normal, e-steven",
        Timeline: "2024-06-22 to 2024-06-25",
        AssigneeAvailability: false
    },
    {
        Id: "Task 13",
        Title: "Task - 29018",
        Status: "Close",
        Summary: "Analyze stored procedures.",
        Type: "Others",
        Priority: "Critical",
        CardTags: "Database, SQL",
        Estimate: 2,
        Assignee: "Andrew Fuller",
        AssigneeKey: "Andrew Fuller",
        RankId: 3,
        Color: "#27AE60",
        ClassName: "e-others, e-critical, e-nancy",
        Timeline: "2024-06-20 to 2024-06-23",
        AssigneeAvailability: true
    },
    {
        Id: "Task 14",
        Title: "Task - 29019",
        Status: "Validate",
        Summary: "Validate editing issues.",
        Type: "Story",
        Priority: "Critical",
        CardTags: "Fix",
        Estimate: 1,
        Assignee: "Robert King",
        AssigneeKey: "Robert King",
        RankId: 2,
        Color: "#8b447a",
        ClassName: "e-story, e-low, e-steven",
        Timeline: "2024-06-21 to 2024-06-23",
        AssigneeAvailability: false
    },
    {
        Id: "Task 15",
        Title: "Task - 29020",
        Status: "Review",
        Summary: "Test editing functionality.",
        Type: "Story",
        Priority: "Normal",
        CardTags: "Testing",
        Estimate: 0.5,
        Assignee: "Janet Leverling",
        AssigneeKey: "Janet Leverling",
        RankId: 4,
        Color: "#8b447a",
        ClassName: "e-story, e-normal, e-andrew",
        Timeline: "2024-06-22 to 2024-06-23",
        AssigneeAvailability: false
    },
    {
        Id: "Task 16",
        Title: "Task - 29021",
        Status: "In Progress",
        Summary: "Implement login functionality.",
        Type: "Feature",
        Priority: "High",
        CardTags: "Authentication",
        Estimate: 4.5,
        Assignee: "Andrew Fuller",
        AssigneeKey: "Andrew Fuller",
        RankId: 1,
        Color: "#7d7297",
        ClassName: "e-feature, e-high, e-andrew",
        Timeline: "2024-06-20 to 2024-06-24",
        AssigneeAvailability: true
    },
    {
        Id: "Task 17",
        Title: "Task - 29022",
        Status: "Open",
        Summary: "Update user profile page.",
        Type: "Improvement",
        Priority: "Normal",
        CardTags: "UI",
        Estimate: 3,
        Assignee: "Janet Leverling",
        AssigneeKey: "Janet Leverling",
        RankId: 2,
        Color: "#7d7297",
        ClassName: "e-improvement, e-normal, e-janet",
        Timeline: "2024-06-20 to 2024-06-25",
        AssigneeAvailability: false
    },
    {
        Id: "Task 18",
        Title: "Task - 29023",
        Status: "Close",
        Summary: "Refactor codebase for better performance.",
        Type: "Improvement",
        Priority: "Critical",
        CardTags: "Refactor",
        Estimate: 6,
        Assignee: "Margaret Hamilt",
        AssigneeKey: "Margaret Hamilt",
        RankId: 2,
        Color: "#27AE60",
        ClassName: "e-improvement, e-critical, e-margaret",
        Timeline: "2024-06-20 to 2024-06-26",
        AssigneeAvailability: false
    },
    {
        Id: "Task 19",
        Title: "Task - 29024",
        Status: "Validate",
        Summary: "Test performance improvements.",
        Type: "Story",
        Priority: "High",
        CardTags: "Testing",
        Estimate: 1.5,
        Assignee: "Steven Walker",
        AssigneeKey: "Steven Walker",
        RankId: 3,
        Color: "#8b447a",
        ClassName: "e-story, e-high, e-steven",
        Timeline: "2024-06-20 to 2024-06-21",
        AssigneeAvailability: true
    },
    {
        Id: "Task 20",
        Title: "Task - 29025",
        Status: "In Progress",
        Summary: "Implement dark mode feature.",
        Type: "Feature",
        Priority: "Normal",
        CardTags: "UI",
        Estimate: 5,
        Assignee: "Robert King",
        AssigneeKey: "Robert King",
        RankId: 2,
        Color: "#7d7297",
        ClassName: "e-feature, e-normal, e-robert",
        Timeline: "2024-06-21 to 2024-06-26",
        AssigneeAvailability: false
    }
];

export let assigneeDetails: { [key: string]: Object }[] = [
    { Assignee: "Vinothkumar Yuvaraj", Capacity: 2.5 },
    { Assignee: "Gokulraj Devarajan", Capacity: 1 },
    { Assignee: "Yaswin Vikhaash Rajaretenam", Capacity: 1 },
    { Assignee: "Revanth Krishnan", Capacity: 1.2 },
    { Assignee: "Harish Raja", Capacity: 0.5 },
    { Assignee: "Aravindh Balakrishnan", Capacity: 2 },
    { Assignee: "Manoranjan Rajendran", Capacity: 1.5 },
    { Assignee: "Vijay Raja", Capacity: 1.75 },
    { Assignee: "Saravanan G", Capacity: 1.9 },
];

export interface PizzaDataModel {
    Id: string;
    OrderID: string;
    Title: string;
    Type: string;
    Size: string;
    Category: string;
    Description: string;
    CardTags: string[];
    ImageURL: string;
    Price: string;
    Date: Date;
    Feedback?: string;
    SentimentScore?: number;
    Emoji?: string;
}

export let pizzaData: PizzaDataModel[] = [
    {
        Id: "1",
        OrderID: "Order ID - #16365",
        Title: "Mexican Green Wave",
        Type: "Vegetarian",
        Size: "Small",
        Category: "Order",
        Description: "Stromboli sandwich with chili sauce",
        CardTags: ["Onions", "Pepper", "Cheese"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-01.png",
        Price: "$4.79",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        Feedback: "",
        SentimentScore: 0,
        Emoji: ""
    },
    {
        Id: "2",
        OrderID: "Order ID - #16367",
        Title: "Peppy Paneer",
        Type: "Vegetarian",
        Size: "Large",
        Category: "Ready to Serve",
        Description: "It's made using toppings of tomato, mozzarella cheese and fresh basil",
        CardTags: ["Onions", "Pepper", "Cheese"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-02.png",
        Price: "$14.99",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        Feedback: "",
        SentimentScore: 0,
        Emoji: ""
    },
    {
        Id: "3",
        OrderID: "Order ID - #16372",
        Title: "Chicken Golden Delight",
        Type: "Non-Vegetarian",
        Size: "Large",
        Category: "Order",
        Description: "Barbeque chicken with a topping of golden corn loaded with extra cheese",
        CardTags: ["BBQ", "Prawn"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-07.png",
        Price: "$14.99",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        Feedback: "",
        SentimentScore: 0,
        Emoji: ""
    },
    {
        Id: "4",
        OrderID: "Order ID - #16374",
        Title: "Chicken Fiesta",
        Type: "Non-Vegetarian",
        Size: "Small",
        Category: "Delivered",
        Feedback: "Good",
        Description: "Grilled Chicken Rashers with Peri-Peri chicken, Onion and Capsicum",
        CardTags: ["Chicken", "Capsicum"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-13.png",
        Price: "$4.79",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        SentimentScore: 0,
        Emoji: ""
    },
    {
        Id: "5",
        OrderID: "Order ID - #16375",
        Title: "Double Cheese Margherita",
        Type: "Vegetarian",
        Size: "Medium",
        Category: "Delivered",
        Feedback: "Best",
        Description: "Margherita with chili sauce and double Cheese",
        CardTags: ["Onions", "Pepper"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-10.png",
        Price: "$11.99",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        SentimentScore: 0,
        Emoji: ""
    },
    {
        Id: "6",
        OrderID: "Order ID - #16379",
        Title: "Chicken Dominator",
        Type: "Non-Vegetarian",
        Size: "Small",
        Category: "Menu",
        Description: "Double Pepper Barbecue Chicken with Peri-Peri Chicken, Chicken Tikka, Grilled and Rashers",
        CardTags: ["Pepper", "Chicken"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-15.png",
        Price: "$4.79",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        Feedback: "",
        SentimentScore: 0,
        Emoji: ""
    },
    {
        Id: "9",
        OrderID: "Order ID - #16383",
        Title: "Margherita",
        Type: "Vegetarian",
        Size: "Large",
        Category: "Ready to Deliver",
        Description: "Lebanese Pizza topped with tomato sauce",
        CardTags: ["Pepper", "Cheese"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-18.png",
        Price: "$4.99",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        Feedback: "",
        SentimentScore: 0,
        Emoji: ""
    },
    {
        Id: "10",
        OrderID: "Order ID - #16384",
        Title: "Pepper Barbecue and Onion",
        Type: "Non-Vegetarian",
        Size: "Medium",
        Category: "Ready to Deliver",
        Description: "Pepper Barbecue chicken with Onion",
        CardTags: ["Onions", "Chicken"],
        ImageURL: "https://blazor.syncfusion.com/demos/_content/Blazor_Server_Common_NET8/images/kanban/menu-20.png",
        Price: "$11.99",
        Date: new Date(new Date().getFullYear(), new Date().getMonth(), 10),
        Feedback: "",
        SentimentScore: 0,
        Emoji: ""
    }
];